(cl:defpackage ros_service_ex-srv
  (:use )
  (:export
   "PRODUCTOFTHREENUM"
   "<PRODUCTOFTHREENUM-REQUEST>"
   "PRODUCTOFTHREENUM-REQUEST"
   "<PRODUCTOFTHREENUM-RESPONSE>"
   "PRODUCTOFTHREENUM-RESPONSE"
  ))

