// Generated by gencpp from file ros_service_ex/ProductOfThreeNumRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_EX_MESSAGE_PRODUCTOFTHREENUMREQUEST_H
#define ROS_SERVICE_EX_MESSAGE_PRODUCTOFTHREENUMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_service_ex
{
template <class ContainerAllocator>
struct ProductOfThreeNumRequest_
{
  typedef ProductOfThreeNumRequest_<ContainerAllocator> Type;

  ProductOfThreeNumRequest_()
    : num1(0)
    , num2(0)
    , num3(0)  {
    }
  ProductOfThreeNumRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)
    , num3(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;

   typedef int32_t _num3_type;
  _num3_type num3;





  typedef boost::shared_ptr< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ProductOfThreeNumRequest_

typedef ::ros_service_ex::ProductOfThreeNumRequest_<std::allocator<void> > ProductOfThreeNumRequest;

typedef boost::shared_ptr< ::ros_service_ex::ProductOfThreeNumRequest > ProductOfThreeNumRequestPtr;
typedef boost::shared_ptr< ::ros_service_ex::ProductOfThreeNumRequest const> ProductOfThreeNumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator1> & lhs, const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2 &&
    lhs.num3 == rhs.num3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator1> & lhs, const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_service_ex

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86be3740681ed62105cc2bccd1e32006";
  }

  static const char* value(const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86be3740681ed621ULL;
  static const uint64_t static_value2 = 0x05cc2bccd1e32006ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_service_ex/ProductOfThreeNumRequest";
  }

  static const char* value(const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num1\n"
"int32 num2\n"
"int32 num3\n"
;
  }

  static const char* value(const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
      stream.next(m.num3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProductOfThreeNumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_service_ex::ProductOfThreeNumRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
    s << indent << "num3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICE_EX_MESSAGE_PRODUCTOFTHREENUMREQUEST_H
