// Generated by gencpp from file ros_service_ex/ProductOfThreeNum.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_EX_MESSAGE_PRODUCTOFTHREENUM_H
#define ROS_SERVICE_EX_MESSAGE_PRODUCTOFTHREENUM_H

#include <ros/service_traits.h>


#include <ros_service_ex/ProductOfThreeNumRequest.h>
#include <ros_service_ex/ProductOfThreeNumResponse.h>


namespace ros_service_ex
{

struct ProductOfThreeNum
{

typedef ProductOfThreeNumRequest Request;
typedef ProductOfThreeNumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProductOfThreeNum
} // namespace ros_service_ex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_service_ex::ProductOfThreeNum > {
  static const char* value()
  {
    return "3dbbdc95f1a704981b9e7b198a21e3bd";
  }

  static const char* value(const ::ros_service_ex::ProductOfThreeNum&) { return value(); }
};

template<>
struct DataType< ::ros_service_ex::ProductOfThreeNum > {
  static const char* value()
  {
    return "ros_service_ex/ProductOfThreeNum";
  }

  static const char* value(const ::ros_service_ex::ProductOfThreeNum&) { return value(); }
};


// service_traits::MD5Sum< ::ros_service_ex::ProductOfThreeNumRequest> should match
// service_traits::MD5Sum< ::ros_service_ex::ProductOfThreeNum >
template<>
struct MD5Sum< ::ros_service_ex::ProductOfThreeNumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_ex::ProductOfThreeNum >::value();
  }
  static const char* value(const ::ros_service_ex::ProductOfThreeNumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_ex::ProductOfThreeNumRequest> should match
// service_traits::DataType< ::ros_service_ex::ProductOfThreeNum >
template<>
struct DataType< ::ros_service_ex::ProductOfThreeNumRequest>
{
  static const char* value()
  {
    return DataType< ::ros_service_ex::ProductOfThreeNum >::value();
  }
  static const char* value(const ::ros_service_ex::ProductOfThreeNumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_service_ex::ProductOfThreeNumResponse> should match
// service_traits::MD5Sum< ::ros_service_ex::ProductOfThreeNum >
template<>
struct MD5Sum< ::ros_service_ex::ProductOfThreeNumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_ex::ProductOfThreeNum >::value();
  }
  static const char* value(const ::ros_service_ex::ProductOfThreeNumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_ex::ProductOfThreeNumResponse> should match
// service_traits::DataType< ::ros_service_ex::ProductOfThreeNum >
template<>
struct DataType< ::ros_service_ex::ProductOfThreeNumResponse>
{
  static const char* value()
  {
    return DataType< ::ros_service_ex::ProductOfThreeNum >::value();
  }
  static const char* value(const ::ros_service_ex::ProductOfThreeNumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICE_EX_MESSAGE_PRODUCTOFTHREENUM_H
